//
//  IMEmojiTapback.h
//  BlueBubblesHelper DyLib
//
//  Created by Tanay Neotia on 5/20/26.
//  Copyright © 2026 BlueBubbleMessaging. All rights reserved.
//


/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMEmojiTapback : NSObject

@property (nonatomic, readonly) NSString *associatedMessageEmoji;
@property (nonatomic, readonly) IMEmojiTapback *counterpart;
@property (nonatomic, readonly) NSString *description;
@property (nonatomic, readonly) IMEmojiTapback *removedTapbackCounterpart;
@property (nonatomic, readonly) IMEmojiTapback *visibleTapbackCounterpart;

// Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities

+ (bool)isValidAssociatedMessageType:(long long)arg1;

- (id)actionStringFormatWithAdaptiveImageGlyphAvailable:(bool)arg1;
- (id)associatedMessageEmoji;
- (id)counterpart;
- (id)description;
- (id)initWithAssociatedMessageType:(long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithEmoji:(id)arg1 isRemoved:(bool)arg2;
- (id)initWithIMRemoteObjectSerializedDictionary:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)reactionStringWithAdaptiveImageGlyph:(id)arg1 isCommSafetySensitiveProvider:(id /* block */)arg2;
- (id)removedTapbackCounterpart;
- (id)visibleTapbackCounterpart;

// Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit

- (bool)isEqualIgnoringModifiersToEmojiTapback:(id)arg1;

// Image: /System/Library/PrivateFrameworks/IMCore.framework/IMCore

- (id)messageForChat:(id)arg1 messageGUID:(id)arg2 messagePartRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 messageSummaryInfo:(id)arg4 threadIdentifier:(id)arg5;

@end
